import { defineConfig } from 'vite';
import tailwindcss from '@tailwindcss/vite';
import fs from 'fs';
import path from 'path';

/**
 * Load the entries JSON generated by your shell script
 */
function loadEntries() {
    const file = '.build/vite-entries.json';
    if (!fs.existsSync(file)) return {};
    return JSON.parse(fs.readFileSync(file, 'utf-8'));
}

/**
 * Normalize entries to absolute paths so Vite can find them
 */
function normalizeEntries(entries) {
    const result = {};
    for (const [name, file] of Object.entries(entries)) {
        result[name] = path.resolve(file);
    }
    return result;
}

export default defineConfig({
    plugins: [tailwindcss()],
    base: '/',
    build: {
        outDir: 'public',
        emptyOutDir: false,
        copyPublicDir: false,
        rollupOptions: {
            input: normalizeEntries(loadEntries()),
            output: {
                entryFileNames: '[name]',
                chunkFileNames: 'chunks/[name]-[hash].js',
                assetFileNames: '[name].[ext]',
            },
        },
    },
});