services:

  apache:
    build: .
    container_name: ivy_apache
    networks:
      - ivy_network
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/public
    ports:
      - "${SERVER_PORT:-8080}:80"
    volumes:
      - ../:/var/www
      - ./sites-available:/etc/apache2/sites-available
      - ./sites-enabled:/etc/apache2/sites-enabled
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini

  node:
    image: node:latest
    container_name: ivy_node
    networks:
      - ivy_network
    working_dir: /var/www
    ports:
      - "${VITE_PORT:-5173}:5173"
    volumes:
      - ../:/var/www
    command: tail -f /dev/null

  mysql:
    image: mysql
    container_name: ivy_mysql
    networks:
      - ivy_network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE:-ivy_db}
      MYSQL_USER: ${DB_USERNAME:-ivy_db_username}
      MYSQL_PASSWORD: ${DB_PASSWORD:-ivy_db_password}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - ivy_mysql_data:/var/lib/mysql
      - ./mysql/ivy.sql:/docker-entrypoint-initdb.d/ivy.sql

  mailpit:
    image: axllent/mailpit
    container_name: ivy_mailpit
    networks:
      - ivy_network
    ports:
      - "8025:8025" # Web UI
      - "${MAIL_PORT:-1025}:1025" # SMTP

volumes:
  ivy_mysql_data:

networks:
  ivy_network:
