version: '3.8'

services:

  apache:
    build: .
    container_name: ${APACHE_HOST:-ivy_apache}
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/public
    ports:
      - "${SERVER_PORT:-8080}:80"
    volumes:
      - ../:/var/www:Z
      - ./sites-available:/etc/apache2/sites-available:Z
      - ./sites-enabled:/etc/apache2/sites-enabled:Z
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini:Z

  node:
    image: docker.io/node:latest
    container_name: ${NODE_HOST:-ivy_node}
    working_dir: /var/www
    ports:
      - "${VITE_PORT:-5173}:5173"
    volumes:
      - ../:/var/www:Z
    command: tail -f /dev/null

  mysql:
    image: docker.io/mysql:latest
    container_name: ${DB_HOST:-ivy_mysql}
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE:-ivy_db}
      MYSQL_USER: ${DB_USERNAME:-ivy_db_username}
      MYSQL_PASSWORD: ${DB_PASSWORD:-ivy_db_password}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - ivy_mysql_data:/var/lib/mysql:z
      - ./mysql/ivy.sql:/docker-entrypoint-initdb.d/ivy.sql:Z

  mailcatcher:
    image: docker.io/dockage/mailcatcher
    container_name: ${MAIL_HOST:-ivy_mailcatcher}
    hostname: ${MAIL_HOST:-ivy_mailcatcher}
    ports:
      - "1080:1080"
      - "${MAIL_PORT:-1025}:1025"

volumes:
  ivy_mysql_data:
    driver: local
