name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # --- PHP setup ---
    - name: Setup PHP 8.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: composer:v2

    - name: Show PHP version
      run: php -v

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Verify Composer dependencies
      run: composer check-platform-reqs

    - name: Run PHPStan
      uses: php-actions/phpstan@v3
      with:
        path: routes/
        php_version: 8.3
        level: 1

    # --- Node.js / npm setup ---
    - name: Setup Node.js (Latest)
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'    # always installs the latest LTS version
        cache: 'npm'             # enables npm caching automatically

    - name: Show Node & npm version
      run: |
        node -v
        npm -v

    - name: Install npm dependencies
      run: npm install

    # Optional: build/test scripts
    # - name: Build assets
    #   run: npm run build
    # - name: Run npm tests
    #   run: npm test
